var data = {
    "children": [
        { "name": "D3.js", "value": 100, "myValue": 20 },
        { "name": "Echarts/js", "value": 77, "myValue": 70 },
        { "name": "JavaScript", "value": 70, "myValue": 60 },
        { "name": "C/C++", "value": 66, "myValue": 5 },
        { "name": "Java", "value": 66, "myValue": 10 },
        { "name": "PHP", "value": 56, "myValue": 36 },
        { "name": "Ruby", "value": 69, "myValue": 0 },
        { "name": "Python", "value": 73, "myValue": 10 },
        { "name": "Windows", "value": 80, "myValue": 60 },
        { "name": "Linux", "value": 90, "myValue": 50 },
        { "name": "Unix", "value": 85, "myValue": 30 },
        { "name": "Mac OS", "value": 12, "myValue": 1 },
        // { "name": "Ubuntu", "value": 21, "myValue": 1 },
        // { "name": "CentOS", "value": 13, "myValue": 1 },
        // { "name": "RedHat", "value": 12, "myValue": 0 },
        // { "name": "JSON", "value": 70, "myValue": 70 },
        // { "name": "Lua", "value": 53, "myValue": 1 },
        // { "name": "XML", "value": 30, "myValue": 30 },
        // { "name": "JQuery", "value": 80, "myValue": 70 },
        // { "name": "WebGL", "value": 45, "myValue": 30 },
        // { "name": "AngularJS", "value": 44, "myValue": 30 },
        // { "name": "ajax", "value": 90, "myValue": 80 },
        // { "name": "Node.js", "value": 78, "myValue": 1 },
        // { "name": "Hadoop", "value": 80, "myValue": 1 },
        // { "name": "Git", "value": 93, "myValue": 60 },
        // { "name": "Shell", "value": 34, "myValue": 1 },
        // { "name": "Go", "value": 54, "myValue": 1 },
        // { "name": "Swift", "value": 24, "myValue": 1 },
        // { "name": "HTTP", "value": 8, "myValue": 5 },
        // { "name": "TCP", "value": 5, "myValue": 5 },
        // { "name": "Android", "value": 14, "myValue": 1 },
        // { "name": "iOS", "value": 10, "myValue": 1 }
    ]
}
